image: ruby:2.4
pages:
  stage: deploy
  script:
  - apt update && apt install -y jekyll
  - gem install jekyll bundle
  - bundle
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
