image: ruby:2.4
pages:
  stage: deploy
  script:
  - apt install jekyll
  - apt install jekyll
  - bundle
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
