title: Private Blog
email: admin@eynet.xyz
description: > # this means to ignore newlines until "baseurl:"
  Ein kleiner Privater Blog für so Dinge zwischendurch.
baseurl: ""
url: "https://blog.eynet.xyz"
twitter_username: urpgb
github_username: elyday
read_more: Weiterlesen
env: production
minify_html: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

paginate: 12
paginate_path: "/:num/"

author_img: /img/author.jpg

navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Galery
    url: /galery
  - text: Categories
    url: /categories
  - text: Tags
    url: /tags

sticky: sticky
sticky_count: 3

plugins:
  - jekyll-feedimage

defaults:
  - scope:
      path: "img/galery/trauermarsch-viersen-15-06"
    values:
      galery: "trauermarsch-viersen-15-06"